"""ajout colonne thumbnail

Revision ID: 290b1f39870b
Revises: f7b995736d22
Create Date: 2026-03-04 19:58:47.853315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290b1f39870b'
down_revision = 'f7b995736d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
